[project]
name = "grokking_my-work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.7.9"
dependencies = [
    "matplotlib==3.1.3",
    "numpy==1.18.1",
    "turicreate==6.2.2",
]
